### ISSUE TITLE
Running Direct doesn't work unfortunately

### ISSUE THREAD

**Issue by Sergong** [matlockx/spotify-playlist#1]
I get the following error on python -m bottle -b 0.0.0.0:8080 main --debug:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/smeeuwsen/Documents/Spotify Playlists/.virtualenvs/spotify/bin/bottle.py", line 3731, in <module>
    reloader=opt.reload, plugins=opt.plugin, debug=opt.debug)
  File "/Users/smeeuwsen/Documents/Spotify Playlists/.virtualenvs/spotify/bin/bottle.py", line 3087, in run
    app = load_app(app)
  File "/Users/smeeuwsen/Documents/Spotify Playlists/.virtualenvs/spotify/bin/bottle.py", line 3032, in load_app
    rv = load(target) # Import the target module
  File "/Users/smeeuwsen/Documents/Spotify Playlists/.virtualenvs/spotify/bin/bottle.py", line 3017, in load
    if module not in sys.modules: __import__(module)
ImportError: No module named 'main'

I must be missing something...

Never mind, discover what was wrong... I didn't have the main.py file.

**Comment by matlockx** [comment]
ok, so I assume that it can be closed?

**Comment by Sergong** [comment]
Yes indeed :-)
